import Navbar from "@/components/navigation/navbar/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { CheckIsPrivateRoute } from "@/utils/route";
import { usePathname } from "next/navigation";
import { headers } from "next/headers";
import Sidebar from "@/components/navigation/sidebar/Sidebar";
import Header from "@/components/navigation/header/Header";
import Navigation from "./navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const headersList = headers();
  const activePath = headersList.get("x-invoke-path");
  return (
    <html lang="en">
      <body className="bg-sweden-500 flex h-fit">
        {/*  && <Navbar />} */}

        <div>
          <Sidebar />
        </div>
        <div className="w-full min-h-screen">
          <Navigation
            isPrivate={CheckIsPrivateRoute(activePath || "") ? true : false}
          />
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
